name: Pytest & flake8 control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"
      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8
      - name: Run tests
        run: |
          pytest > log_pytest.txt
      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: log_pytest
          path: log_pytest.txt
      - name: Run flake8
        uses: py-actions/flake8@v2
      - name: Test Print fake password secret
        run: |
          echo "Fake password secret: ${{ secrets.PASSWORD_FAKE }}"
        shell: bash
